### ISSUE TITLE
delete_messages: Http(InvalidRequest(BadRequest))

### ISSUE THREAD

**Issue by bbigras** [zeyla/serenity#194]
I got `Http(InvalidRequest(BadRequest))` while trying to delete one message. My bot should have the right permission. I tested with all 3 branches.

```rust
let message_ids = vec![
    MessageId(some_id),
];

let channel = ChannelId(some_channel_id).get().unwrap();

if let Channel::Guild(c) = channel {
    c.write().delete_messages(&message_ids).unwrap();
}
```

```
thread 'serenity client' panicked at 'called `Result::unwrap()` on an `Err` value: Http(InvalidRequest(BadRequest))', src\libcore\result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::result::unwrap_failed<serenity::error::Error>
             at C:\projects\rust\src\libcore\macros.rs:23
   9: core::result::Result<(), serenity::error::Error>::unwrap<(),serenity::error::Error>
             at C:\projects\rust\src\libcore\result.rs:772
  10: test_serenity::{{impl}}::on_ready
             at .\src\main.rs:77
  11: serenity::client::dispatch::handle_event::{{closure}}<test_serenity::Handler>
             at C:\Users\bbigras\.cargo\git\checkouts\serenity-3ee4e93465cd5f21\cae0147\src\client\dispatch.rs:398
  12: core::result::Result<(), serenity::error::Error>::map<(),serenity::error::Error,(),closure>
             at C:\projects\rust\src\libcore\result.rs:468
  13: serenity::client::dispatch::handle_event<test_serenity::Handler>
             at C:\Users\bbigras\.cargo\git\checkouts\serenity-3ee4e93465cd5f21\cae0147\src\client\dispatch.rs:394
  14: serenity::client::dispatch::dispatch<test_serenity::Handler>
             at C:\Users\bbigras\.cargo\git\checkouts\serenity-3ee4e93465cd5f21\cae0147\src\client\dispatch.rs:61
  15: serenity::client::bridge::gateway::shard_runner::{{impl}}::run::{{closure}}<test_serenity::Handler>
             at C:\Users\bbigras\.cargo\git\checkouts\serenity-3ee4e93465cd5f21\cae0147\src\client\bridge\gateway\shard_runner.rs:121
  16: threadpool::{{impl}}::call_box<closure>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.0\src\lib.rs:95
  17: threadpool::spawn_in_pool::{{closure}}
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.0\src\lib.rs:753
```

**Comment by hsiW** [comment]
You are not able to delete just one message using the `delete_messages` function

**Comment by hsiW** [comment]
For deleting one message you'd want to use https://docs.rs/serenity/0.4.1/serenity/model/enum.Channel.html#method.delete_message

**Comment by bbigras** [comment]
It works now. At first I was trying to delete more than 1 message but I think maybe some pinned message was causing a problem. or maybe it was before I switched to 0.50.

**Comment by zeyla** [comment]
We could defer to the `delete_message` function if it's detected that only one message is provided, so let's keep this issue open.

**Comment by acdenisSK** [comment]
[`c7aa27d`](https://github.com/zeyla/serenity/commit/c7aa27dbb64e64d70c7f13725c79017c4bba1c95)
