### ISSUE TITLE
serenity 0.4 doesn't recover from panics (PoisonError)

### ISSUE THREAD

**Issue by bbigras** [zeyla/serenity#250]
If I have a panic in one of my commands serenity doesn't recover and I can't use any command anymore. After the panic, using a command results in a PoisonError.

EDIT: I don't need serenity to recover. recovering or exiting the program so it can be restarted would be fine too.

```rust
#[macro_use]
extern crate serenity;

extern crate dotenv;

use serenity::framework::standard::StandardFramework;
use serenity::model::*;
use serenity::model::GuildId;
use serenity::prelude::*;

use dotenv::dotenv;

use std::env;

struct Handler;

impl EventHandler for Handler {
    fn on_ready(&self, _: Context, ready: Ready) {
        println!("{} is connected!", ready.user.name);
    }
}

fn main() {
    dotenv().ok();

    let mut client = Client::new(&env::var("DISCORD_TOKEN").expect("token"), Handler);

    client.with_framework(
        StandardFramework::new()
            .configure(|c| c.prefix("~"))
            .on("test", cmd_test)
            .on("panic", cmd_panic)
    );

    client.start().unwrap();
}

command!(cmd_test(_context, message) {
    message.channel_id.send_message(|m| {
        m.content("test ok")
    });
});

command!(cmd_panic(_context, message) {
    panic!("test panic");
    
    message.channel_id.send_message(|m| {
        m.content("panic")
    });
});
```

log
```
thread 'serenity client' panicked at 'test panic', src\main.rs:45:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'serenity client' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore\result.rs:916:5
```

serenity 0.4.7
rustc 1.25.0-nightly (f62f77403 2018-01-10)

**Comment by zeyla** [comment]
Should be closed by 5138193, will be released in a new version in a few days.
