### ISSUE TITLE
Bot stops working on some special input

### ISSUE THREAD

**Issue by Caemor** [zeyla/serenity#309]
My prefix is ~ and when my bot receives the following message then it stops working:
```
~존재감이 없는~~  <@98938149316599808> 님이 소리쳤어요!!!

<@98938149316599808>:  **hi**
```

Running it with RUST_BACKTRACE=1 gave the following error:
```
[2018-04-17][07:44:18][cælia::helpers][INFO] CAELIA is connected!
thread '<unnamed>' panicked at 'byte index 49 is not a char boundary; it is inside '이' (bytes 47..50) of `존재감이 없는~~  <@98938149316599808> 님이 소리쳤어요!!!

<@98938149316599808>:  **hi**`', /checkout/src/libcore/str/mod.rs:2234:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::str::slice_error_fail
             at /checkout/src/libcore/str/mod.rs:0
  10: <serenity::framework::standard::StandardFramework as serenity::framework::Framework>::dispatch
  11: serenity::client::dispatch::dispatch
  12: <serenity::client::bridge::gateway::shard_runner::ShardRunner<H>>::run

```

**Comment by Caemor** [comment]
Fixed on the newest master branch.
